version = 0.1

[default]
[default.local_invoke]
[default.local_invoke.parameters]
parameter_overrides = "Env=local"

[dev]
[dev.deploy]
[dev.deploy.parameters]
parameter_overrides = "Env=dev"
stack_name = ""
s3_bucket = ""
s3_prefix = ""
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["SeleniumFunction=xxxxxxxxx.dkr.ecr.ap-northeast-1.amazonaws.com/xxxxxxxx"]

[prd]
[prd.deploy]
[prd.deploy.parameters]
parameter_overrides = "Env=prd"
stack_name = ""
s3_bucket = ""
s3_prefix = ""
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["SeleniumFunction=xxxxxxxxx.dkr.ecr.ap-northeast-1.amazonaws.com/xxxxxxxx"]
